### ISSUE TITLE
[1.18.1] Durability Doesn't Work

### ISSUE THREAD

**Issue by itsdinkd** [ochotonida/artifacts#120] opened 2021-12-29 03:40 UTC
I've set durability on almost every artifact, yet, it looks like it is not working.

![image](https://user-images.githubusercontent.com/35115304/147625094-3ab5b704-f124-4fec-a84e-a8d7d0831a39.png)

no durability as shown in tooltip.

Also, I am getting this weird line in curios inventory
![image](https://user-images.githubusercontent.com/35115304/147625275-101a6c75-4d60-4c72-a823-e67df6486593.png)

![image](https://user-images.githubusercontent.com/35115304/147625267-c13493b1-518d-4b7d-8227-db4065816fda.png)

**Comment by ochotonida** [comment] 2021-12-29 11:44
Durability is still working as intended, it seems the issue is purely visual. I've uploaded a patch that should fix the issue.

**Comment by itsdinkd** [comment] 2021-12-29 20:22
Is there any way to request that the durability is at least shown on the item so players don't think there is a bug when there artifact breaks/disappears?

**Comment by ochotonida** [comment] 2021-12-30 14:51
That's currently not possible, but I'll reopen this issue as a reminder to add something like that in the next patch.

**Comment by itsdinkd** [comment] 2021-12-30 18:04
Thanks!

**Comment by ochotonida** [comment] 2022-03-06 16:41
Seems like I forgot to close this issue, if an artifact has durability enabled it will now always show a durability bar.

**Closed as completed by ochotonida** 2022-03-06 16:41 UTC
Labels: bug
