### ISSUE TITLE
Flamingo fall damage bug

### ISSUE THREAD

**Issue by Pantheris2019** [ochotonida/artifacts#177] opened 2022-09-28 22:41 UTC
**Describe the bug**
Flamingo slow fall to ground still invokes fall damage tick.

**To Reproduce**
1. Acquire and equip flamingo artifact.
2. fall and activate flamingo slow fall.
3. when you hit the ground, the landing still invokes the fall damage tick, possibly accruing 20 hearts of damage.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 1.18.2 - 4.2.0
 - Forge: 40.1.80

**Comment by ochotonida** [comment] 2022-10-01 12:55
I can't seem to reproduce the issue and/or this might be intended behaviour, I'm not entirely sure if I understand your issue correctly from your description. Could you clarify the issue you're having a bit?

The Helium Flamingo does not provide a slow fall effect, rather it allows you to swim in the air for a limited amount of time. If you are in the air when the time runs out, you will fall to the ground and receive fall damage as normal, for the height you were at when the effect ran out.

**Comment by ochotonida** [comment] 2023-02-18 11:50
I'm closing this issue as I haven't been able to reproduce this issue. If you're still having this issue, feel free to open a new issue with additional information or reopen/comment on this one.

**Closed as not planned by ochotonida** 2023-02-18 11:50 UTC
Labels: bug
