### ISSUE TITLE
Running Shoes auto-step effect not disabling after unequiping.

### ISSUE THREAD

**Issue by Jason-c-o** [ochotonida/artifacts#54] opened 2021-01-31 01:25 UTC
After equipping the running shoes, I was still auto-stepping over 1 block tall barriers. It was also happening whether I was sprinting or not, including walking backwards.

After restarting the game with them unequipped, the effect was removed.

MC 1.16.5
Forge 36.0.1
Artifacts 2.7.5

**Comment by ochotonida** [comment] 2021-01-31 12:55
Do you happen to be using any other mods that could be modifying step height? This is very likely a compatibility issue, since the running shoes reset the step height when unequipped, so a full mod list would be appreciated

**Comment by ochotonida** [comment] 2021-02-16 21:51
I'm gonna close this for now, since I don't have enough information to reproduce this issue, and I have yet to receive any similar reports. Feel free to reopen if you have more info

**Closed as completed by ochotonida** 2021-02-16 21:51 UTC
