### ISSUE TITLE
Foot slot not appearing.

### ISSUE THREAD

**Issue by Allycat2208** [ochotonida/artifacts#209] opened 2023-07-12 17:05 UTC
I am using the newest version of this mod as well as the curios mod. in videos it showed that once you downloaded this mod, a foot slot would appear. However, there is no foot slot.

**Comment by ochotonida** [comment] 2023-07-12 20:55
I can't seem to reproduce this issue with just Artifacts and its dependencies on the latest Forge version, are you using any other mods? A log file would also help.

**Comment by ochotonida** [comment] 2023-08-13 15:32
Closing this issue since I don't have the necessary information to reproduce it. If you're still having this problem feel free to open a new issue, although please fill in the issue template if you do so.

**Closed as not planned by ochotonida** 2023-08-13 15:32 UTC
Labels: bug
