### ISSUE TITLE
[1.19.2 Forge] Bug - pocket_piston

### ISSUE THREAD

**Issue by GitJhopa** [ochotonida/artifacts#221] opened 2023-09-02 19:19 UTC
artifacts:pocket_piston - When a player has 1-2 pieces of this artifact, then when I hit him, he constantly knocks me back. But why is it throwing me away?? I should be knocked back when the player hits me, not me.

**Comment by ochotonida** [comment] 2023-09-10 16:32
I can't reproduce this issue with just Artifacts on Minecraft 1.19.2. This could be a compatibility issue, if you're using other mods please verify it can be reproduced with just Artifacts or try to find which mod is causing it.

**Comment by GitJhopa** [comment] 2023-10-03 02:02
> I can't reproduce this issue with just Artifacts on Minecraft 1.19.2. This could be a compatibility issue, if you're using other mods please verify it can be reproduced with just Artifacts or try to find which mod is causing it.

You must be wearing armor with the SPIKES enchantment.

**Comment by GitJhopa** [comment] 2023-10-03 02:03
And this bug also works with bows, when I use the Open Parties And Claims region mod in player regions where PVP is turned off, then players using a bow and a piston can push players and animals out of private, although they cannot use a sword. This is a bug.

**Comment by ochotonida** [comment] 2023-11-21 13:29
I'm closing this issue for now, as it doesn't seem like I have enough information to reproduce it. If you're still having this problem, feel free to open a new issue, but please fill in the template next time. If you do so, try to reproduce the issue without irrelevant mods first, to narrow down which mod is causing the problem.

**Closed as not planned by ochotonida** 2023-11-21 13:29 UTC
Labels: bug
