### ISSUE TITLE
Water does not push blocks

### ISSUE THREAD

**Issue by jasnowizard** [ochotonida/artifacts#271] opened 2024-04-28 21:58 UTC
I recently updated my mods this morning and I noticed that water was not pushing blocks and creatures in my farms. I rolled back a couple of different mods to find out which one caused the issue, and it appears that the latest version of Artifacts causes this issue. 
The block and items just stay static but they do float.

place down a water source and let run along the floor
throw blocks in the the water flowing water and you will see they don't move

I am running Minecraft java 1.20.1
atrifacts version 9.5.1
forge 47.2.30
All my other mods
AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar            JadeAddons-1.20.1-forge-5.2.2.jar
 amendments-1.20-1.1.22.jar                         jei-1.20.1-forge-15.3.0.4.jar
 appleskin-forge-mc1.20.1-2.5.1.jar                 JustEnoughResources-1.20.1-1.4.0.247.jar
 architectury-9.2.14-forge.jar                      letfishlove-2.0.3.jar
 artifacts-forge-9.4.2.jar                          LetSleepingDogsLie-1.20.1-Forge-1.2.0.jar
 astikorcarts-redux-1.20.1-1.1.7.jar                lootr-forge-1.20-0.7.33.83.jar
 AttributeFix-Forge-1.20.1-21.0.4.jar               Mekanism-1.20.1-10.4.6.20.jar
 balm-forge-1.20.1-7.2.2.jar                        MekanismGenerators-1.20.1-10.4.6.20.jar
 BetterAdvancements-1.20.1-0.3.2.162.jar            MekanismTools-1.20.1-10.4.6.20.jar
 BetterF3-7.0.2-Forge-1.20.1.jar                    modernfix-forge-5.17.0+mc1.20.1.jar
 biomeinfo-1.20.1-1.6.jar                           moonlight-1.20-2.11.12-forge.jar
 Bookshelf-Forge-1.20.1-20.1.10.jar                 moreadvancementsmod-1.3.0-1.20.1.jar
 c2me-fabric-mc1.20.1-0.2.0+alpha.11.5.jar          MouseTweaks-forge-mc1.20-2.25.jar
 caelus-forge-3.2.0+1.20.1.jar                      NaturesCompass-1.20.1-1.11.2-forge.jar
 carryon-forge-1.20.1-2.1.2.7.jar                   netherportalfix-forge-1.20-13.0.1.jar
 catalogue-forge-1.20.1-1.8.0.jar                   noisium-forge-2.0.2+mc1.20-1.20.1.jar
 catloaf-1.1.1-1.20.x-FORGE.jar                     oculus-mc1.20.1-1.7.0.jar
 chargedcharms-1.20.1-2.0.0.5-FORGE.jar             Paraglider-forge-20.1.3.jar
 charmofundying-forge-6.5.0+1.20.1.jar              petnames-1.20.1-3.3.jar
 charms-2.0.2-1.20.1.jar                            Placebo-1.20.1-8.6.1.jar
 chickensshed-forge-1.6.0+mc1.20.1.jar              portal-linking-compass-forge-1.0.1+mc1.20.jar
 Chunky-1.3.136.jar                                 Quark-4.0-441.jar
 clickadv-1.20.1-3.8.jar                            QuarkOddities-1.20.1.jar
 cloth-config-11.1.118-forge.jar                    questsadditions-1.4.3a.jar
 collective-1.20.1-7.54.jar                         regrowth-1.20-46.31.2.jar
 Controlling-forge-1.20.1-12.0.2.jar                responsiveshields-2.3-mc1.18-19-20.x.jar
 CorgiLib-forge-1.20.1-4.0.1.1.jar                  Searchables-forge-1.20.1-1.0.3.jar
 craftingtweaks-forge-1.20.1-18.2.3.jar             shieldmechanics-1.20.1-4.3.jar
 CraftTweaker-forge-1.20.1-14.0.38.jar              Shield_Overhaul-FORGE-MC1.20.1-1.0.3.jar
 CreativeCore_FORGE_v2.11.27_mc1.20.1.jar           SimpleBackups-1.20.1-3.1.4.jar
 cristellib-1.1.5-forge.jar                         SimpleStorageNetwork-1.20.1-1.10.0.jar
 cupboard-1.20.1-2.6.jar                            sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
 curios-forge-5.9.0+1.20.1.jar                      sophisticatedcore-1.20.1-0.6.21.609.jar
 elytraslot-forge-6.3.0+1.20.1.jar                  sophisticatedstorage-1.20.1-0.10.21.793.jar
 embeddium-0.3.14+mc1.20.1.jar                      spidersproducewebs-1.20.1-3.3.jar
 EnchantmentDescriptions-Forge-1.20.1-17.0.14.jar   storagedrawers-1.20.1-12.0.3.jar
 Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar       supplementaries-1.20-2.8.10.jar
 entityculling-forge-1.6.2-mc1.20.1.jar             suppsquared-1.20-1.1.14.jar
 Fallingleaves-1.20.1-2.1.0.jar                     totw_additions-1.3.1-1.20.x-forge.jar
 FastFurnace-1.20.1-8.0.2.jar                       totw_modded-forge-1.20.1-1.0.5.jar
 FastLeafDecay-31.jar                               Towns-and-Towers-1.12-Fabric+Forge.jar
 FastWorkbench-1.20.1-8.0.4.jar                     trade-cycling-forge-1.20.1-1.0.10.jar
 ferritecore-6.0.1-forge.jar                        TravelersTitles-1.20-Forge-4.0.2.jar
 fishermens_trap-2.1.2.jar                          twilightforest-1.20.1-4.3.2145-universal.jar
 flib-1.20.1-0.0.12.jar                             valhelsia_core-forge-1.20.1-1.1.2.jar
 forgivingvoid-forge-1.20-10.0.0.jar                valhelsia_furniture-forge-1.20.1-1.1.3.jar
 ftb-library-forge-2001.2.1.jar                     valhelsia_structures-forge-1.20.1-1.1.2.jar
 ftb-quests-forge-2001.4.1.jar                      valhelsia_tweaks-forge-1.20.1-0.1.0.jar
 ftb-teams-forge-2001.3.0.jar                       villagernames-1.20.1-7.3.jar
 ftb-ultimine-forge-2001.1.4.jar                   'WaterloggedChests1.20.1(Forge)vs1.0.4.jar'
 GeophilicReforged-v1.2.0.jar                       waystones-forge-1.20-14.1.3.jar
 HammerLib-1.20.1-20.1.25.jar                       WaystonesTeleportPets-1.20-1.20.1--1.2.jar
 Highlighter-1.20.1-forge-1.1.9.jar                 Xaeros_Minimap_24.1.1_Forge_1.20.jar
 Iceberg-1.20.1-forge-1.1.21.jar                    xaeros_waystones_compability-1.0.jar
 improvedfishing-1.0-1.20-1.20.1.jar                XaerosWorldMap_1.38.4_Forge_1.20.jar
 inventorysorter-1.20.1-23.0.1.jar                  YungsApi-1.20-Forge-4.0.4.jar
 Jade-1.20.1-forge-11.8.0.jar                       Zeta-1.0-16.jar

**Comment by florensie** [comment] 2024-04-28 22:08
This has to be a bug caused by Expandability. I'll look into it tomorrow. Can you reproduce it with just artifacts installed, or does this only happen with your combination of mods?

**Comment by florensie** [comment] 2024-04-28 22:14
Found the issue, it's pretty obvious in hindsight. I'll push out a fix tomorrow.

https://github.com/florensie/ExpandAbility/blob/master/neoforge%2Fsrc%2Fmain%2Fjava%2Fbe%2Fflorens%2Fexpandability%2Fmixin%2Fforge%2Fswimming%2FEntityMixin.java#L58

**Comment by florensie** [comment] 2024-04-29 16:09
Fixed in https://github.com/florensie/ExpandAbility/commit/847da2d512359c1f98c3d13aa5301b8901329ca2.
Expandability v9.0.4 and v10.0.1 for 1.20.1 and 1.20.4 respectively should be up on curseforge soon.

**Closed as completed by florensie** 2024-04-29 16:09 UTC
Labels: bug
