### ISSUE TITLE
Requires a dependency I can't find- dependency issue

### ISSUE THREAD

**Issue by DorkE28** [ochotonida/artifacts#297] opened 2024-07-04 01:13 UTC
**Describe the bug**
It's an "error loading mods" because of a dependency that isn't working. The dependency is expandability and it's "not installed"
**To Reproduce**

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: [10.0.12]
 - Forge/Fabric Api: [1.20.4]
 - [other relevant mods...]

**Comment by ochotonida** [comment] 2024-07-04 07:47
I can't reproduce this issue with just Artifacts and it's dependencies. ExpandAbility is a required dependency for Artifacts, however, it comes included with the mod so this is probably caused by something else. Can you send over a latest.log file?

**Comment by ochotonida** [comment] 2024-07-21 11:43
I'm closing this issue since I don't have enough information to reproduce it. Feel free to open a new issue or comment on this one if you're still having this problem.

**Closed as not planned by ochotonida** 2024-07-21 11:43 UTC
Labels: bug
