### ISSUE TITLE
Bug with Helium Flamingo and Ender Pearls.

### ISSUE THREAD

**Issue by OmIAm** [ochotonida/artifacts#233] opened 2023-11-24 17:16 UTC
**Describe the bug**

Where you are looking when you begin a flight with this item is where the ender pearl takes you if thrown during the flight.  If you are looking straight down, start flying, fly a distance away and throw a pearl out in front of you, it will send you straight back to where you started.

**To Reproduce**
1) Look at a specific place.
2) Begin flight and fly away.
3) Throw pearl out in front of you.
4) You will teleport back to where you were looking when you began the flight.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 1.19.2-5.0.2
 - Forge/Fabric Api: Forge	43.2.14

The only other mod that *MIGHT* affect swimming is: ExpandAbility	7.0.0

**Comment by ochotonida** [comment] 2023-11-26 17:51
I can't seem to reproduce this issue, although it looks like you're using an outdated version of Artifacts. Can you check if this still happens after updating to 5.0.3 or later?

**Comment by OmIAm** [comment] 2023-11-26 20:22
Ok, I'll try to narrow down what's causing it.  It must be an interaction with another mod.  I'll let you know if I figure it out.

**Comment by ochotonida** [comment] 2023-11-27 17:17
Did a bit more testing myself, looks like it's part of the same issue that got fixed in version 5.0.3. It only happens after switching dimensions, that's why I wasn't able to reproduce initially.

**Closed as completed by ochotonida** 2023-11-27 17:17 UTC
Labels: bug

**Comment by OmIAm** [comment] 2023-11-27 17:22
Thank you very much! :)
