### ISSUE TITLE
Posted exact error with mod

### ISSUE THREAD

**Issue by fluid46** [ochotonida/artifacts#295] opened 2024-06-21 21:57 UTC
[21Jun2024 20:43:53.645] [Worker-Main-3/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecraft:mineable/pickaxe (from artifacts-forge-9.5.11.jar)] as it is missing following references: #minecraft:mineable/pickaxe (from artifacts-forge-9.5.11.jar)

Forge 1.20.1

**Comment by ochotonida** [comment] 2024-06-21 22:18
Can you post a full log file please?

**Comment by fluid46** [comment] 2024-06-21 23:33
Yes, give me a sec

**Comment by ochotonida** [comment] 2024-07-21 11:42
I'm closing this issue since I don't have enough information to reproduce it. Feel free to open a new one if you're still having this problem, although please fill in the issue template next time.

**Closed as not planned by ochotonida** 2024-07-21 11:42 UTC
Labels: bug
