### ISSUE TITLE
Water doesn't push entities

### ISSUE THREAD

**Issue by RandomGuy91** [ochotonida/artifacts#279] opened 2024-05-09 19:01 UTC
**Describe the bug**
Flowing water does not push any entities, (mobs, items) except for players. This seems to be related to a similar error that was marked as closed: https://github.com/ochotonida/artifacts/issues/271

**To Reproduce**
Place flowing water in the world and throw and item or place a mob in it. It will not move. 

**Game Environment**
I am using artifacts version 2.5.0 alongside curios api, architechtuary, and cloth config. (All of which I believe are required dependencies) I am on forge, version 47.2.0.

**Comment by ochotonida** [comment] 2024-05-09 22:24
The versions you state you are using cannot be correct, Forge 47.x.x is for Minecraft 1.20.1, and Artifacts 2.5.0 is only available for Minecraft 1.16, 1.15 and 1.14. Can you double check that you're using the latest version of Artifacts for the Minecraft version you're using?

**Comment by RandomGuy91** [comment] 2024-05-10 07:09
Sorry, I meant 9.5.0!

**Comment by florensie** [comment] 2024-05-10 17:57
This is a duplicate of #271, which was already fixed.

**Comment by RandomGuy91** [comment] 2024-05-10 17:58
Sorry, I want using the updated version 😅

**Comment by ochotonida** [comment] 2024-05-28 20:01
Forgot to close this

**Closed as not planned by ochotonida** 2024-05-28 20:01 UTC
Labels: bug
