### ISSUE TITLE
[Crash] Does not work with Forge 40.0.18

### ISSUE THREAD

**Issue by rabrunos** [ochotonida/artifacts#136] opened 2022-03-17 18:42 UTC
**Describe the bug**
Artifacts are not working with Forge 40.0.18.
But it's working with Forge 40.0.17. (I tested with the same files.)

**To Reproduce**
1. Install Artifacts and their Dependencies
2. Start game

**Game Environment**
 - Artifacts: 4.0.5 - 1.18.2
 - Curios: 5.0.6.3 - 1.18.2
 - ExpandAbility: 6.0.0 - 1.18.2
 - Forge: 40.0.18 - 1.18.2

**Log Files**
latest.log
https://mclo.gs/ETpX1Z3

debug.log
https://mclo.gs/kMcDIRM

**Comment by ochotonida** [comment] 2022-03-17 18:50
Thanks for the report. This issue is a duplicate of #135, version 4.0.6 of Artifacts should fix the issue.

**Closed as completed by ochotonida** 2022-03-17 18:50 UTC
Labels: bug
