### ISSUE TITLE
Farmer’s Delight Interop

### ISSUE THREAD

**Issue by CJM7** [ochotonida/artifacts#165] opened 2022-09-13 18:43 UTC
FD has a mechanic where killing animals with the knife doubles drops and introduces new food items, however the gauntlet artifact overrides these changes, making it impossible to attain certain foodstuff with it equipped.

**Comment by ochotonida** [comment] 2022-09-13 19:12
Can you check whether this still happens when you manually set a mob on fire and then kill it with a knife while not wearing the gauntlet? The fire gauntlet doesn't modify the loot mobs drop, it only sets them on fire, so it seems more likely to me that this is caused by another mod.

**Comment by CJM7** [comment] 2022-09-18 01:47
Did some more testing, was able to find the bug, which exists in immersive
weathering(?!), will update if the new version fixes it.

**Comment by ochotonida** [comment] 2022-10-01 12:04
I'll close this issue for now, since it doesn't seem to be related to Artifacts at all. Feel free to open a new issue if you think this is not the case.

**Closed as not planned by ochotonida** 2022-10-01 12:04 UTC
Labels: bug
