### ISSUE TITLE
Slashblade mod incompatibility

### ISSUE THREAD

**Issue by EmanuMora** [ochotonida/artifacts#172] opened 2022-09-15 21:57 UTC
**Describe the bug**
Whenever an exact move with the katana of the Slashblade mod is made, the game crashes and sends the user on the main menu

**To Reproduce**
With all the katanas, continuous press of the right click

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: [1.18.2-4.0.7]
 - Forge: [40.1.71]

[crash-2022-09-15_23.26.07-client.txt](https://github.com/ochotonida/artifacts/files/9579281/crash-2022-09-15_23.26.07-client.txt)

**Comment by ochotonida** [comment] 2022-09-16 07:56
I can't reproduce this issue (using the latest version of Slashblade, you didn't specify which version you're using), and the crash report doesn't have anything to indicate this issue is related to Artifacts. Did you verify this issue doesn't happen when you don't have Artifacts installed? Are you using any other mods?

Also, if you're reporting an issue to a mod, please check that you're using the latest version for the Minecraft version you're using. You're running 2 versions behind.

**Comment by ochotonida** [comment] 2023-02-18 11:39
I'm closing this issue as I haven't been able to reproduce it, and it likely isn't related to Artifacts. If you're still having this problem and removing Artifacts fixes it, feel free to open a new issue. Though if you do so, please try to reproduce the issue without irrelevant mods first.

**Closed as not planned by ochotonida** 2023-02-18 11:39 UTC
Labels: bug
