### ISSUE TITLE
Weird incompat with VanillaTweaks

### ISSUE THREAD

**Issue by D-Bigboy-302** [ochotonida/artifacts#151] opened 2022-06-19 14:12 UTC
**Describe the bug**
When Artifacts is ran alongside VanillaTweaks, https://www.curseforge.com/minecraft/mc-mods/vanillatweaks
effects from artifacts will flicker on and off from player updates such as switching between items in hotbars, picking up an item, breaking blocks, etc.

**To Reproduce**
1. Load Artifacts and Vanilla tweaks together
2. Put on any artifact that provides a potion effect. For my case, bunny slippers. 
3. Optionally have some mod to display potion effects on hud, helps illustrate the issue.
4. Put any item in hotbar.
5. Switch between item and hand and watch potion effects.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: [Forge - 4.1.0]
 - Forge: [40.1.51]
 - I also have Optifine installed as well. Though, it doesn't seem to have an effect through my testing.

**Comment by florensie** [comment] 2022-06-19 20:18
Just to clarify, is this only with artifacts that work with status effects?

**Comment by D-Bigboy-302** [comment] 2022-06-20 00:58
Yes! I should have clarified that, apologies. It's only artifacts that provide potion effects

**Comment by ochotonida** [comment] 2022-08-14 17:16
I can't seem to reproduce this issue, although it's possible I'm misunderstanding what the problem is. Does this also happen with the water breathing effect from vanilla's Turtle Shell? It applies the potion effect the same way artifacts do, so it might not be an issue with this mod specifically.

**Comment by ochotonida** [comment] 2023-02-18 11:45
I'm closing this issue as I haven't been able to reproduce it, and it likely isn't caused by Artifacts. If you're still having this issue and it only happens with potion effects specifically applied by artifacts, feel free to either open a new issue or reopen/comment on this one.

**Closed as not planned by ochotonida** 2023-02-18 11:45 UTC
Labels: bug
