### ISSUE TITLE
Eternal Steak not giving any hunger or saturation

### ISSUE THREAD

**Issue by bigchadguy** [ochotonida/artifacts#312] opened 2024-08-05 05:34 UTC
**Describe the bug**
Was playing on a BigChadGuys Plus world which has the artifact mod included and my power went out while I was closing my game the other night. When I logged back on some parts of my inventory weren't saved properly but everything else seemed fine, except for one of the artifact items I have called "Eternal Steak." The bug is that the item when eaten no longer gives any hunger or saturation points when consumed. When hovered, the item displays the appropriate number of drumstick icons to indicate how much saturation/hunger points the food gives but unlike other foods the drumsticks on the bugged Eternal Steak are all blanked out now, just greyed out drumsticks. 

This is a screenshot of what the item looks like when hovered ingame.
![bugged eternal steak](https://github.com/user-attachments/assets/7576999c-74e9-49e8-ac94-a99dc4684d9d)

**To Reproduce**

- I do not know how to reproduce the behavior but I believe it happened because the saving of my world while exiting the world was interrupted by a power outage and my pc turning off before the process was fully completed.

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 9.5.12
 - Forge/Fabric Api: Fabric API 0.92.2+1.20.1
 - Modpack: BigChadGuys Plus (Non Cobblemon)-2.3.1.zip

**Comment by ochotonida** [comment] 2024-08-05 17:20
If this is actually caused by the game being shut down while saving then there's not really anything I can do to fix this, although I'd expect a lot more to be broken in that case. Could you execute `/data get entity @p` while holding the steak and then send over your latest.log file?

**Comment by ochotonida** [comment] 2024-08-13 15:42
I'm closing this issue, since this doesn't seem like something that could be fixed on my end.
Feel free to open a new issue if it turns out that there's some reliable way to reproduce this.

**Closed as not planned by ochotonida** 2024-08-13 15:42 UTC
Labels: bug
