### ISSUE TITLE
Reflective champion-thorn pendant crash

### ISSUE THREAD

**Issue by Jackiecrazy** [ochotonida/artifacts#122] opened 2021-12-30 09:06 UTC
**Describe the bug**
Attacking an entity with the champions mod affix "reflective", while wearing a thorn pendant with 100% proc chance, will crash the game. I'm presuming it stems from some recursion.

**To Reproduce**
1. Configure the thorn pendant to have a 1.0 trigger chance
2. Equip the thorn pendant
3. Attack a reflective champion (unsure if thorns will work)

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Artifacts: 2.10.4
 - Forge: 36.2.22
 - Champions: 2.0.1.8

Logs:
[crash-2021-12-30_16.32.20-server.txt](https://github.com/ochotonida/artifacts/files/7792222/crash-2021-12-30_16.32.20-server.txt)

**Comment by ochotonida** [comment] 2021-12-30 14:50
Unfortunately I can't seem to reproduce this issue with just Artifacts and Champions. Are you able to consistently reproduce this issue? It's possible that there's another mod at play here.
The crash report isn't of much help either, unfortunately. There's an error while forge is handling the exception, which prevents most of the actual exception from getting logged.

**Comment by ochotonida** [comment] 2022-08-14 17:11
I'm gonna close this issue since there hasn't been any activity on it for a while and I'm unable to reproduce it. If you or someone else is still having this issue, feel free to open a new issue or reopen this one.

**Closed as completed by ochotonida** 2022-08-14 17:11 UTC
Labels: bug
