### ISSUE TITLE
Crash when opening Chest 

### ISSUE THREAD

**Issue by realBritakee** [ochotonida/artifacts#208] opened 2023-07-08 15:04 UTC
**Describe the bug**
when opening a chest from a village with lootr mod installed etc. the game is crashing 

**To Reproduce**
1. Start the game with Artifacts and Lootr 
2. Open a chest
3. Crash

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: Latest 1.20.1 7.0.1
 - Forge: 47.1.0
 - Lootr 1.20.1 Latest
 
 Crash Report
https://pastebin.com/XmR7eU2w

**Comment by florensie** [comment] 2023-07-08 15:20
Looks like this is a duplicate of #207. You say you're on 7.0.1 (which fixes this), but your log shows 7.0.0.

**Closed as not planned** 2023-07-09 09:39 UTC
Labels: bug
