### ISSUE TITLE
Creepers explode through walls while too close to player with Kitty Slippers

### ISSUE THREAD

**Issue by Catomax262** [ochotonida/artifacts#203] opened 2023-06-06 09:49 UTC
**Describe the bug**
For some reason, creepers explode even if they are not seeing the player only if the player approaches them too much. This led to a portion of my base being missing without myself even noticing the Creeper.

**To Reproduce**
1. Approach a Creeper while having Kitty Slippers on at least 1 block of distance
2. It explodes (even if it just casually walks to you from behind a wall)

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below. Try to reproduce the issue without irrelevant mods first. Otherwise, include a complete list of mods or the name and version of the modpack you're using.
 - Artifacts: 4.2.1
 - Forge: 4.0.2.4
 - none

**Comment by ochotonida** [comment] 2023-06-28 17:51
I'm unable to reproduce this issue, were you able to reproduce this behavior without any mods other than Artifacts and Curios?

**Comment by ochotonida** [comment] 2023-08-16 12:21
I'm closing this issue since it doesn't seem like I have enough information to reproduce it. Feel free to open a new issue or comment on this one with more information if you're still having this problem.
In particular it would be nice to know if this issue can be consistently reproduced, preferably with only artifacts installed.

**Closed as not planned by ochotonida** 2023-08-16 12:21 UTC
Labels: bug
